[supervisord]
logfile=logs/supervisord.log
pidfile=/tmp/supervisord.pid

[program:ingestion]
command=python ingestion.py
directory=.
autostart=true
autorestart=true
startretries=10
stderr_logfile=logs/ingestion_stderr.log
stdout_logfile=logs/ingestion_stdout.log

[program:api]
command=uvicorn app.main:app --host 0.0.0.0 --port 8002
directory=.
autostart=true
autorestart=true
startretries=5
stderr_logfile=logs/api_stderr.log
stdout_logfile=logs/api_stdout.log
